services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    environment:
      KEYCLOAK_ADMIN:
      KEYCLOAK_ADMIN_PASSWORD:
    command: start-dev
    ports:
      - 8088:8080

  nmshd:
    image: ghcr.io/nmshd/connector:latest
    container_name: nmshd
    environment:
      CUSTOM_CONFIG_LOCATION: "/config.json"
    ports:
      - 8082:80
    volumes:
      - ./docker/nmshd/config.json:/config.json:ro
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:6.0.6
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    volumes:
      - mongo-db:/data/db
    restart: always

volumes:
  mongo-db:
